In [10]:
import numpy as np
arr1 = np.array([[20,40],[60,80]])
print(np.append(arr1,100))


[ 20  40  60  80 100]
[20 40 50 60 80]
[20 60 80]


In [13]:
print(np.insert(arr1,[1,2],[70,90],axis=0))

[[20 40]
 [70 90]
 [60 80]
 [70 90]]


In [20]:
print(arr1)
print(np.delete(arr1,1,axis=0))

[[20 40]
 [60 80]]
[[20 40]]
