In [4]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.size(arr))
print(np.mean(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

150
10
50
5
30.0
[ 10  30  60 100 150]
[      10      200     6000   240000 12000000]


In [9]:
#example
price = np.array([100,150,200,300,350])
quantity = np.array([12,20,13,43,21])
total = (np.cumprod([price,quantity],axis=0))
print(total[1].sum())
total = np.multiply(price,quantity)
print(total)

27050
[ 1200  3000  2600 12900  7350]
