In [3]:
import numpy as np

arr1 = np.array([10,20,30,40])
arr2 = np.array([50,60,70,80])

print(np.add(arr1,arr2))
print(np.subtract(arr2,arr1))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))


[ 60  80 100 120]
[40 40 40 40]
[ 500 1200 2100 3200]
[0.2        0.33333333 0.42857143 0.5       ]
