In [6]:
import numpy as np
arr1 = np.array([[10,20],[30,40]])
arr2 = np.array([[50,60],[70,80]])
print(np.concatenate([arr1,arr2],axis=0)) #vertical concatenate
print(np.vstack([arr1,arr2]))
print("--------------------------------")
print(np.concatenate([arr1,arr2],axis=1)) #horizontal concatenate
print(np.hstack([arr1,arr2]))

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
--------------------------------
[[10 20 50 60]
 [30 40 70 80]]
[[10 20 50 60]
 [30 40 70 80]]


In [13]:
import numpy as np
arr1 = np.array([10,20,30,40,50,60])
b=np.array_split(arr1,3)
print(b[1])
arr2 = np.array([[10,20,30],[40,50,60]])
print(np.array_split(arr2,3))


[30 40]
[array([[10, 20, 30]]), array([[40, 50, 60]]), array([], shape=(0, 3), dtype=int64)]
