In [14]:
import numpy as np
arr = np.array([20,40,10,90,110])
print(np.sort(arr))
a=np.where(arr == 90)
print(a)
print(np.where(arr % 2 == 0))

[ 10  20  40  90 110]
(array([3]),)
(array([0, 1, 2, 3, 4]),)


In [18]:
arr2 = np.array([10,20,30,40,50])
print(np.searchsorted(arr2,20))

1


In [22]:
arr3 = np.array([20,40,50,60,70])
new = [True,False,True,False,True]
fa = arr3>30
print(arr3[fa])

[40 50 60 70]
